# Generated by Django 2.2.24 on 2023-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
