# Generated by Django 3.1.14 on 2023-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230518_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
